//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


     [MetadataType(typeof(TimeMetadata))]
    public partial class Time
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<int> DeviceSerial { get; set; }
        public class TimeMetadata
        {
            public int Id { get; set; }
            [DisplayName("Time from ")]
            public Nullable<System.DateTime> From { get; set; }
            [DisplayName("Time to ")]
            public Nullable<System.DateTime> To { get; set; }
            [DisplayName("Serial Device Number")]
            public Nullable<int> DeviceSerial { get; set; }



        }


    }
}
